apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-backend-protocol":"tcp"},"name":"envoy","namespace":"projectcontour"},"spec":{"externalTrafficPolicy":"Local","ports":[{"name":"http","port":80,"protocol":"TCP"},{"name":"https","port":443,"protocol":"TCP"}],"selector":{"app":"envoy"},"type":"LoadBalancer"}}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  creationTimestamp: "2021-01-09T23:01:10Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  
  name: envoy
  namespace: projectcontour
 
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30006
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 31417
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: envoy
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
