#@ load("@ytt:data", "data")
---
apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: e2e-workshop
spec:
  title: End to End Workshop
  description: A workshop exploring the end to end experience of VMware Tanzu
  vendor: tanzu.vmware.com
  difficulty: beginner
  duration: 30m
  url: https://github.com/tomsfrt/e2e
  authors:
  - Chris DeLashmutt <cdelashmutt@vmware.com>
  - Anand Rao <raoan@vmware.com>
  content:
    image: #@ "harbor.{}/tanzu-e2e/eduk8s-e2e-workshop:latest".format(data.values.ingress.domain)
    files: #@ "github.com/{}/e2e/home?ref={}".format(data.values.git.account,data.values.git.branch)
  session:
    env:
      - name: MYSQL_REGISTRY
        value: #@ data.values.registry.dockerhub
      - name: HARBOR_PASSWORD
        value: #@ data.values.harbor.adminPassword
      - name: CONCOURSE_USERNAME
        value: #@ data.values.concourse.username
      - name: CONCOURSE_PASSWORD
        value: #@ data.values.concourse.password
    namespaces:
      budget: x-large
      limits:
        default:
          cpu: 1000m
          memory: 1Gi
      secondary:
        - name: concourse-$(session_namespace)
          role: admin
          budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
    dashboards:
    - name: Whiteboard
      url: https://excalidraw.com/
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: kpack-user
      rules:
      - apiGroups:
        - kpack.io
        resources:
        - builds
        - builders
        - images
        - sourceresolvers
        verbs:
        - get
        - list
        - watch
        - create
        - delete
        - patch
        - update
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: kpack-user
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: kpack-user
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: e2e-user
      rules:
      - apiGroups:
        - e2e.tanzu.vmware.com
        - projectcontour.io
        resources:
        - harborprojects
        - concourseteams
        - httpproxies
        verbs:
        - get
        - list
        - watch
        - create
        - delete
        - patch
        - update
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: e2e-user
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: e2e-user
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
    - apiVersion: e2e.tanzu.vmware.com/v1beta1
      kind: HarborProject
      metadata:
        name: $(session_namespace)
        annotations:
          training.eduk8s.io/objects.crd.scope: Namespaced
      spec:
        name: $(session_namespace)
    - apiVersion: e2e.tanzu.vmware.com/v1beta1
      kind: ConcourseTeam
      metadata:
        name: $(session_namespace)
        annotations:
          training.eduk8s.io/objects.crd.scope: Namespaced
      spec:
        name: $(session_namespace)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: concourse-web
        namespace: concourse-$(session_namespace)
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: concourse-web
      subjects:
      - kind: ServiceAccount
        namespace: concourse
        name: concourse-web
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: concourse-web
        namespace: concourse-$(session_namespace)
      rules:
        - apiGroups: [""]
          resources: ["secrets"]
          verbs: ["get"]
      
  logo: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAWUAAAFbCAMAAAA6K29UAAACBFBMVEVHcEwAwdUDmOSAySRP1eMcn+EAmecAl+N8xCEAld99ye8bRZEByN15vyATnuMHld2UkpYAzuOOze55eHym2PI6rOYfzd8AktuO5e7f78nC5veUzE4AkqKlpae34fKn6/K43YkGxdml1Gtbjxhp3ekAwtYNy9/L5qt1xOy88PW0v9TI0OBYuOQbRpHO568xVpnHx8pEZaJdu+oAxdkAbqU00eJWuOl1c3eFg4clpOQlTZMAnew/0N9+lr9NtehWdKsNltqf2fAJmuJ4d3uCy+tsx+io1nRog7R+xiqHz+GXpsI0q+aJyTicrc4douJ/ujaBxS0qpuNxw+tp3OivxstycXVCr+YfR5B5eHs80eEOkKmEkKiTzUoqf6sussAzWJvR1MwElaRaqsSpzXt+xSSJyDoNo7MHcqZ6wCRgqcWd1fIDw9hilh8bhbt7e34skGwEerZ0pjdflR9bkBk30N+JtlIVx9qkqLJCsOW+4vOr3+wcRY+Mi46DlYlkd50FdqWWlphspSQMiMi+yrhvoDNx0OqizG2GzSyM0NsbRZJZjhhPlDcAkdoAwdV4viAaQopxcHQAbaMAkaBajhgAluEAktwAyt8aQ40AxNgAkdkAlN94d3t6wSAbRZEAwNQAkNkAfr1BkUcei4FEo1UmpH4qf2cMsbILl69fsEBTjiZKijADt8UkNEK2AAAAjHRSTlMAf5/ff3/f39/ff9/f35+ff98/fz9fn98/Pz9f3n8/P1+fX98/3p8/Pz8/Pz+fX39/f3/f359ff3+fn99ff39/f1/f319ff3/maD9/n39fX59/f38f33/fn41/hJ9ff59/n18/n3+fn59/f3+fn19/339/n39/f1+fX0juXwQ/75+f36Sfn5+/qr+/nynkWiUAACLWSURBVHja7F1bc9rWFmYYg4YYw0GDb5RA3UkJ2KROME6K73Ea54zTdGwncTKe2G7SyfVMzvghM01e8pA+nRkIzRmrGFrj/tRys9GWtNde0pYAyaxHDwj509L6vv2ttSWXyyYxNvIT+YfbiUuufpiL8YS/8B/yT/f/mOnjbG4eh44KRyqUC4VQH2fz8nimUAstlAuFfj6blceFAh3lQtU/0ceZMy6NzBwVQJRr4U8MxPtQcXHeWdBRLlSPQiOpPlzGOU+GJB3l+jXwz/bzmTOPGbncKhz9fDbKedhcblyHUD+f9XBeYuaooMKQiXK9boz0ccbWipAaP0wu93lQh3bzHxW0AoVy/XMzs2N9GPVxns5cbkY/n/HaTRl4lPs8CNSKpl9BTdA0+fEH8Mdn+jyolceJEICZf+JdXEOK+OnfqPbzGafdZAVggZb+/irwtZmRPg9iOK+1eE5BlwcsM30eZGm3prGZGEgxboMQfIn6+dy46aFk9C+gyg14iMR5r88szhvA3fAgD553XQdrNyrnGeBB/7nlQW2/4kzvJt7pIy4mD57HfI4zOO+S2eXnHOq61EiIl/P6PMhKuln/UZWex1jOM6DrQudG19VqBVhAF/gOz7BD/BPnIZ/jsyF6HsPrPHOWOUfO58GxEcivME0IjI2cYx6Md+6fj3fmcvYm53XQqGSVphEnDn7FE7B2syC5UjDNzjhuwG4MSqyqZcZZHJKMThvMrXFet0xgxvLHOYO5LM6zeKEQn4V40CGDubB2q3Ge9c2M1CzUGndAPscZjYwOCSrQmipU7Y0z7Fd01FyHdV3Bb1ucxxJwr6nDjU+WrrMlzvCcUFeGuuPvwB5jyHY8yPIrZrvUwF9wkK5jarfumQjxWZAH7VOfxxjGI0ceJ7fvrtTCs53k03W250Em5xnP46TbJ+UbIfnc6XPMgyDnVbk4LxnwtjBu4CwEl2LG68YANFhQDU3cT/VyHsN+BUetSLt9eUVIwrBlPHjE2xezMo+t4rxk0FvOq+LE585ELNJ1PepvWOhXpAM+Ka8dldX3EZ58tpe/McYavOTJY6Gcp0a54r3Oozds5G9Yqd0CgpSHQ3Bz8GBqIOEHdd1AqlfyGNZuPBirOU8rOHkQyufafbjQE3nMmI3l4rw8Lsp8+Xw/AfNgt3UdPJjGpYfS7lEpjw9JyHHwIGswd6GrtaJLnKcVJxUvj96AN1x1b919yTrOA7QblM41XcdhcLDmqbvBgxz7mhCcV4awlKC6EQz3ZP0zaCCGQL4Y4NJukGwLZi7kvHScJcmbE3lwZuzt7OCAXcq62dg0qN1Gm1acGAAFns/Ng/NEbwyax8HGO18eg5wntO3OZA5arEjzAdE6vulE3z3OOAe+PJagDCUsZTEAiWnJF0haxjmWD+amWD1THs6D8tgXSKsLOHRRyt4AHw92bTB3DBqGqnKt+dOgXyEENTNTDMyDeiPHk8+seR3L8vlbK/Y1oTlPG2foi2U+HoR7Et9ahfKC3xr/OAhrN7DFJ0K6Li95eXgQ8mhCty0rGT/4acUizpHHo3k052nnswDqOit4sOq/2WF3iItzYe2mwXmaB8mBC3Kv6brO8sf1JMzkW9ivENzoLAwH5q3TdUoerFpv0T0gspmLa9OQXyGN6hu5EGFdJwTN48GO+KALZ1Ys12wszHneoO7sY/CgwJXPMh4M/dCRJXZLaljIeaPGRoeY/gZX3Wjls/9Dh9yiutTg2teUhv2KgOHxLBH0N/Kcus5/VO3k1PXNEM++JjiPBZ6Mq/Oghf5GorOtqTHjtUIMCPzaDc7n1Qrkb/DwoE0ClLblinfYjB+JLIHqhSufrZJuH807lugWLGtDkzG8apm/oYqPD/iPsTi4a1oeA1Kr9p9zjFSoI7YEKUXJa1o+T+0P3uM/ynTJHJiToMySzKkVZD57LdN17fgwWCwt8h/mSrE4uD/JXStA6ve5t2MWFLvYdtAH8aAJdePXwWKxOM19mMn6YYqDv/LmsfWcZ2AVz61onjXQucJ9msvHRV6YRTcoYVffx1wWxvAq6G/wbFBx7Q42weG+1acbxymVHhktzmC7uc55EZe1EcmAysb4IOPkfhPk4vEy7znOFVthDGZ4NpZvJFZHPoP+hkHmvfnoFJoSb2GeHDw9VNGA1EiCnMe1zUnvOgXSdYYGc5+dgcxfmBdLRcMwJwOjUme1G4MHQXbQuSLabadfDZl1vnO7U5QfTM8yEOY8i7QbjDOk2PUO5v5PDkzpjklluRHTOvLYB3Je2tWNSIOTNYd61A4JDB/9TQ0Slwx7sCTDrxh2dStAXaenil0jUJ7jK8vHRf3lB9zXVBaCmYirexHJMKY/kDxIlNLi4BTPOV0jUL6Cy+NO+xV64zrYT0E6g+vEXX7MZRhdIQrGNCaPvVZtzTNT10EVrc6DMb3QXDNHLaMOlWb4FdddvRKwrqus5pg4T5d03+YItcxermvvSTdny3SHdV1Zmmed7Z1jswrzsg4ihTmPa/u/ZfkMDXAc+ob1FGYOj1mHWh6GlGg3tZvhfM773DF8YTaumEm1DEpvqC/RZe0Gr1DBAY7VD0y38jT2DZ/CPaL0lAC1MjwK5PF1Vy8H1PGVBCCbFwmUHxkuzNew5Hd7ntqNsN4/5g5oeiEA5GARm4M6JCEgViJCj/kVeoM+kOSj/wNTjwiUjdIfWZaBhsDdCsVNHHbZJaiDuW7znTRQEdJNjEC59/wKAzyoqeuENNIwMrouwR4l7LMf51HyWVdlXjRlXbKPvCMyFbVfYa88BnRdeTWC8x8MtlgV1Z3eDvBI9uQ8HA9W3iDVgbHCTJoYRbpSCRIojwbsi3Ezn8m6IWWQStdYYV4u4VS3SIjlw/cuu8dNYl5U2kTm4SNDsy9zSKuI1HHesO1RduWIZA66cIXZkGJGt/wCEu6c7BMknc+HkYlohP4Uapk6JBBZlavlyl0HoCwSPvnhFlLrGmmxYkv7G+LCV7YcgLLLTfxLHnomlngV8xyy5ZchCoYv7ASUSaqhL7JJ09JAi3UdW5Y3JaSHZafCfEisscLIdYn+Fiu65RckCHnTEShHiKVJJWOZYYRt+YXnkSdkqyBTh87oy8d865Jp5FXaJm4ur0N2LG4SKHuQiln/6Ce5Rr+GVMtuZ4DsyiDXJWiYMORHZ8/I/AlO9NgrLhAiQxCRt7xelJeRSvACycZJh6AcEZBLrWWudckcck2y5MiCoaA/iV4yyEa2zs1SaBNjs4yjCdvRX4V4bijdyedpsZLNluOr3JLHbpEmFPMhUjHr3Cy1jJyBJlt+0pZjUFZYGdvcdo9W7COnk4ilaFkIOwdlD9I44Bj9JFt+gHG64jhv+Wy1JRlqserZLHWPbPkt4u4ryeMglEnFjG2x6irMd5ANLVHOEdJhxkEoKxgH22LVo5inDbX85mMOQpkcmAJuU+MtVuzOFPJMnFSWa/SHXJeQhbmIV8ykiQG1/IgzuesolEknH91ixdOfwZbfBUehHCbXJUvI8oqnP2wHwIktP9q6hN4EMjj6qVibA3PLDmz5Uaj9xI2tr1gnn1TLJeyAnMdhKJNdIJ/IrRUUahm5LYVo+TlLLdcjJiAVM7mLFVuYsVusFC0/h5Xlmk4l/EazDSNsL8tTcaaDfxrYFquhx1ugt766T5w2IKe4V8s4K0yx+RSnmLG7/ERipX/IVsvhraXNlUZ4lrb015fxn9fWnrdibe3ncZ1fj7/e22nH3h57puHNYRk3BLFvoMU6h9R/CrUMbyQRl1beHvz9pR0Hb1e2dQxvXF7bGPr81+d2/DW0sXYZ/fXkztPo/8mIPt3Zg42XsIUt1insMzG2sZs8XeHt4MEXjci+3QzjIH419Fkjhl6hgBbVEJ8i/SKNXpdIbqRhhGqxkl8B5hixLT9RG+JToJnDBZd/1IS4BfSPLJyTNIhbGQ3gvEl0guaxTj5m9BPd8sPJSRBjBM6XNwCMGzhvQDiLIMYMnJOkfb5l4roE2/K7gGn5RXIMjJs4U+vj+BMGxg2cn9CYMPaChXETZxFlZWANI0RhRrf8MGr59qcvqMg+0/6NrxEYN3D+WvPrzzAYN3Cm/D7ZYs3R73+5Yi4hCrPimRjIlp+2ZTV88AUZWc1HiH6FBLkG81caX9/FglynQc3Xr2wiZdSU3hbrMlYtM1t+sWD2CzqyL1V37biyIg+9qgvlejx/rhQdQxvjTJDr2q0ZOxrCTuuFfVsEyhJ2Fyu7MGMf4LVEmhjqy3zzkxrJnZ3XzdjZeam8BFnFyx+/G1KICVK1XV5TSI+h78hrrMAx+mKPeCNTek/5AY2XT8bI/V9b3NaPXrr0nMDLTyXI2ZevyWxdf60AmizOBMg1YaxBcOOkjCZg/hBVQKxREUSSG7VgdpdxLbc7yH2+ei1pN7yLVgFy9q0WjYtvs7RsloM89OoX2ln8IsdZBnMsSmB8CaVBoupXyq0g28doS751UZAbJWLwgFzkE06qTRE4Z8/+zXE5eN9AJ/yN/JNnCf9UDh70hq2wHOeo6i1vW8gWK/r5C1pqme5Ib8GjN0ECY2gZPSWvG9nTT24gFx2KZcuGmviiLxgvFpPLvaeqi4Btse7rKcyKa0JH2QOOkf2UZWvh9r8p+/BLpYTTlGhUwdf6tAy4KPtVceE2DUZ3Yb3qwUozuDAr6gtdLQehxurtAxnpsSW62E7npm5uL0bgaqGuGo3lSVgXyETqqz7vQbZY0QPfaquIPo4Ug1p+sU+q1cbkVUo0f2G3DXNaXpQVIE9e/P5GLb6/OEWHeVxelE9Bo/781QdKmBUMQj5egN5indLzdB30gBy0yy+nAvnjrT8p8XBdAXOtZjzRBnn98a3fW3Hr8SQN5icPnqkyc/0h7ef/vKFkyxeKcuJDDvboGf3EPomHKMsK51U8UJZZ143fqfGv5idetrnytyGtmrz++KH8a7f+S6nN//5NfftfpP/8DaXyi/5D3tX4NJVl8caipTHSDQKlFYFSmwJMdCXKAChTLEAiKlIQCRl1dwB1dhizFYtrYja6q7NmtzWutWHLVLoq6qj/5L7X9r13v++5r+La9iaTSeh7vb5fzzvndz7uOUdEKdbRz5Fi7QWn/ARZBItfnGgHo9xomcDfSMagr/tR4r5LBMwmK9mhxVKOsmO8jSPMs8DzlefhKVb8WDE05Yd7npYoW/RXjjLCNF4booxQuFuXSpri4ODgwaJUEzCHi8Kc+81Syh0KKFu8hBDm6SQwYHQZnGKFpvxGk/wCOQ8jzqaj/Gv0wWHGMqdp3iCEGVXKRZCjD/pQ7XHpPks17zDowuHi3cLtLdV8nR9GT774ExC77z5Dym+an/Jr+jOplA2U/y6mU+2EMN9E1EUB1MU+AvYoTjVuFm5jmbECyg8kdO6bNuodYPglfMYM7q5z3l7KDwtiLKCcDEP5DzLWasJcEGUkdhGlFcSiDtwgHtPQhfkNy4odRlUTd5nCfFUQsAF31+mFpvy4F+K/bwarbfqZIcowlC2d8QYXZcfdKGXseqOoUrWEeYf13sNQNoUZVxlYnVoGWvopEFGo0GOx5SzGlk3bh4oyEOUlVGVMYph+S50H0IV5Ef/TJKow6pRRNoUZDxph6Yrkvu6yY8bD5af8RlmiDET5yb8tlXFAVjp0UFfM+Num+Ywmw2jrUUf5qnHzHXspVhhjJlr9TQHZMqaqIgZQS4ooX1m6YXkzb57+QzbJe1D/SiJccM5Sy9hbD0T5bBtTMWPHeLKzUBrcB4srcYl1twsLYowy1fKPiij/QCROfr4CkOU+UmXssBQGBOV5Te3NsxXztK1+lFyXDprywyMoWMrP5HEn2lU1xg8nQMUDAr2sqYznTDYGQLmx7Y9L19lcDk+xutuBivm7MtU33hMDY8sxplqG6WUM5hMSUWZxDI1lsMPxEI2B1W48xhgVVpQoqG0FpVjPQosKBGx5lKmWgdYPgVkGMosva2vVgGlJGWUM5ra/xNrVGTNogAk03E+0wcdiy3uZahnk+2Ew35Bc2RelKYa2EmzHAuT7YblCDWheALLMFKu9Ajncs48IUI4uHiTXtwSTMG3nbYgoL1J/nnz+/DUPZcb2B7Ht/W2cmi7iFCtXMUO66xBBJb5ajghSfgKUmYugYv1vi3d/iItBLgQ2aFHWUH6dfsVBmbVwlTPexq7NwP2SFwswf4MdybfXE4NgNpH/Ftff2m2h/GO6APOHdEII8t0oHZIrovw6nS7AbAtlJPo5ZiuUAYjkQ1N+wlN+kdLfHztAKF/qJVHWYf6YFqN8lxE9KqH8IV2E2R7KjusllANECBKlrllwdx0WhNeA3TQWRFrKQDnmYOnlQXKR0QkN5fRbDWQhygWQGUpZW2vpwvrI1svU9oOkg1lXwPj99gb+Z7z4hH/eXJ5iJY5T8VN++DgjIka1l0U8wByjgHJhCfRyMTcVZVGgmWDp9o9LNjiGjvKnAsipDRGryvAZ87DsFOvvX8LYsrgN/iz7oCeMLzscV+Uol0A+KgI5nf6XOl/W153Uu+fvUqnUHZFkZcpIsQJjHZKeGEaqKmIP5YiBEpfJ3aLSJuY6ZIGcDs7YQnkjtf1JAzlV53DwA0ZgxsywbcfsnfIjdFSMHVOBouwxUFoTgswyfI4uBGQCZjDKgVRxzZEZOOyhXcDDUgzGDK5bzojsbVNpMqi3yQ7KTd4PBkjMEsTeRT7InRjI6WDcBsodoSLIIbKAESv93LKfYiWGDdhK+aEfx+ygHEu+MlCa5JILNshHUZBfvfv02I7GmCuJcoAyRrhfAu37MiyOdOyHsWVGl9ESlcsP2UF5KPnaAOoh1+7dZ946E0/8csC4eSeVarGDcksJ5Q1atrBQRoTPmMWxIGjKb1bSBt8wf16/Osp+b/K9+cb7mF71s+hd/v2PjJs1mhCykZHqKSkMyvgRTkLWdop1GNoTQ9LVutHLYswwlPuT+WyapzJuSUF2rBv3bhMGDIiyoTBCrTSzwrvrAFOs5ACTPlspvxfTfL3tUUdZv/UVW2X0Fe3eoqgYetlQzW9I3QpEOcBTy1R3HX7ASJhvgg6y7XbLmj8bnQa83aood2uvQcZUzMFlyu6xvWpalHcKAqlc9XKkpDC261ger60BJoRitpfyY00+N7gcJswgD7vwFlgq4yEF8jPhN5ii/GGblEiYh22Icoh1EAXapkKYYoXWOE/LNzN+de8AEZNjhdGROP6A/vNks29NYTarl88WQf6VygNgSQBTlN+UwDolj+Kj33DKEOUWts0ANigUGDhwyg/w4pj2D/FMAJW1pXcg+95yLAzPZPAZIHJpBTHeUTIJqaw1PBKW7aNTrNBTrMcFNI9/nMQNqEz30AF+AMrGXZlXlM6AoIy4fv9JkVYMgnIgxbd9lDcmGvnHp8RQtkyk/NghQEuYm+EoN5s3PQmSsQgAyj7rpl+emFIJP/Fg6guOKBN5OHvddcBseQtSmG4Mh82bqnn+d9w1bynlYhOKeSu2VlLN85KbrfC9th45HCdTBMzS7S2Qt09yHh2vwBxpBKZYp3iGUVCtvwc0bMBvQoZaQNGyQNZ9RguyYBfsfksp68rc9OFSoQnY/RPWHT280AL0FCs3xQpt7kcEMbjcfMJLSTMUZB2WsKVjg4Cjqw7fGiH9CGigU5WnID+LB9jRmxvJt9kTg09nmi3YmuUPSV2NxOPxcLxDEo4zrj6lBDPs6tkMLMXK9Uugp/xmwaO5rB/e65G0jGvyeCkdhOSWgg8lp93RFMk6xRhSoYDktHtHwASZxy+KYVlgUSKvu85Z6OlW6NgDVDXLlPMAeqWfcjFkWiO8huahwlR4TSrOp9ArewQX4qk4wTAnTid26Ck/8AgPbY2h4Hm4MaxuD3qdVWviQ4PywTVeF5LwI+y6TmR/FLzAEW7sIoBeNyaMy56xlWI1afE1YMovBh1HQ8Ks4dzPYH3+fg920Rgv96HhnGCcgFh+hF+EERIUZg3nOYaY9swFsIvGxKoF83sFkXx2+RC4J8Y0cLQSA2YNwyG8TW1TbIi4YIyfYiro5wSqoH2T8XUi09dJ7I8iqGHYMocp6I65FuICCchgq4TXXBilcPZ6YmSlwwb8HhxGTaIjC/39sVh//0JE+yyPf+bn8zMDx/Xb8XgikYjHb6+Tn1Ega6IawGHUJHrjTt2cturubNCf9cieB+tHmeT7JeyzwrZ6YogOCzEommwxCd8MBSV3Bdd8EssmXiBejRUlvuAzZmZXIlun/GCTryeAMHvZzkAXFGYeq54AwgzzEfFQhoAxs9wPcE+MLVi8BNMaQwCcvUN+EIfgCzKXUvecBOAcOtkDehhsFmvW1Q5LsRZdafAYwD22Jl83eiQ4ez2it2J5TYZzcH1ZtH9rQIJzKNAKfBS8vQC478txBlvmBjEapSk/3o0NApy9DTLNI8ZZgnEB5xYBzqGWVvCD+KH+AmOAyfGXdgrkXCqz/JoW2ALt9SxAOrYvx9eDPF2xDNm/o44t0KFAXYfCY5QzwMReyk91OknjaARHWqN1o/DpAwygNV6XgM95aK0jyJtG6+paFR8CeoqV7q4Dnk4SERfIQUQ6Njq7tzBIY9bGJI1wIn5bW+v/XNf/F08sK+/foRPljZ9+2tBpc4eNB4iBkhisTuEWW97c3H/t2DwM5cyoowYXNsAkIyj9/Ou1/ZubaO6p2Hlk8+X+4anTwr6JGMpbj2sTZWAPI02cT08N73+5abggw5ubl4ePHT8vHZeNoZx3tdcgykPY6ywdT9Z3/vix4cubep/8K1OnYWNvcb281VB7IA+4gNYPXb2np47Nw/fAa5iS7uZaA7kZBzkZ2Y1NcL6czLoHagvkMVc+CSxJLGO1YzVMml5yj9USyE2EJIuKmMtZDRlin5FasoDU0+/S1Ei87kOX5qEaUspu4uH3fbNbNpbcyVUzFpB6dO+F3eOL5FvjqhELOD6S/DL6Ql9+arPasIBNZ8jnHmncxe3GyBcnUxM+IGX5XOO77P5kCZhrwAe8QMrWrrsKpAMEKjes7DVBgVyu5QtPTq6KA7cXvF/6h/1/Wz6SwCbFBHZ5dVI0czc8uXrTmeMOfjSVFKEz8rtqCb4+n483/LS0OuufPs05b67SSBfmea84c6V5086joq9pJF+gvKeaUW5IKlk+n9OY1+1cwWejr2r46gibQ72dwnzahOtz66lKsnwSF2HFnIqu/5fLOVeNT7qcxBTT3Pdq3mb1wtxMKmVJwJeaFFtvFV8fqud/BqM2E9UJ8oSiY91JApm7iHx6jpzJ6+xUU1Yj96oR5HskyJL8SKeTwhHVvT7yN3haL7aAlHPibqo+kP0u0udzC+kUjSLBI+hfod6nFj6pwijoUFItBrlCYdgp0Si53Dk1C1h9UVDKzZVZPoB1o66RzOKkeWSV+YADLrVoZxdJL5hyelNNNfvPZEifqKqioFQyNeMWHqQ5Wg/SuT6nRHdT/wwyCnqmiqKglBBJfL6jTqCQdol5iJxMJqvI1W7YUnIJaBGt5x3Up31ARQtYPVFQ2r0VP9r3OVJAD9nyD1lrzxfOIXyxNU5pwz1q9OKpKEZxMSdjfNhqp/NhVWEBaW9AbHI665V0ra9s50R2orUyLB8lPONl+XzycMeKWjhlqwp8QE9GLRi2QmoASR6EYQElzomqmahCy0dZM6e8Qc1MPZSS8H74CreA1HnbjJigdlFO8wxgF8UoKG0B91W0BRx3K1o+ypRdhGwTplizMyxmPWqu6Nce7SSzmmJ2GqYd6zBoI9pZPKcYVqngShjVIBj95gObs9HRpfqZWrGAqo9CWbEDXeC9Zg6oWUCyFjQ/UqFRUCqkLCnRpuQRZPm4DFBiAcnUTdZdkZUwje6sUrElZfkk3oVUp4st4D2XGvv5StceSinfU+IJUMvH5yeKPmAllmiQJYBZmc+n6FiXz7UvENKcrzwLSHVZ2jegZr2cXcp7HlL8DqqSutKcE4qQSipc6FhEl41dLypaQHdeqXjhq/P59qklU+m42jk724YVo6BjZBQ0W0nOSRPlWIsPs/v+190V7LQNBFE3hsSpMBKIlqaRQogQFAn5UhWpohci4FIEqZRjbk0lJK499AvgQnxqKowsvrWHAgWP7c2z17szmWN7yGaw5+17M2/iY+27bA6YO/SV8spJRkBi/6ofYXddLyj4yeiIBoEPOQiIOgzaGpAvO83dfAS8S45oCJkFRV9DdEjWAbWQLiRo3cgYUjwEvc/kmhuelvl4lN1QP2BNQJJXafdyDQKsosiXzQEVCFg351eujlijzdTCyJepOilU0H3jDsTyyAceeQA3UwsgIKiC3nBXQasYoNXAAfMnYVIc8awRcJ80U5cx5PPOdRxjByxDBAFvOCMgtY40qmimFkDAOB9SiSOeMQck/QdVM9XFhPcypTlE/YBsSzNqHUHNZEiMMHnO+D4Je8jn9/QdJuWG2M1/D6NkmlkiIJGUIxD5wrHO4wTgmP5RQwICUuvIAdhMLcn5lKRS0a2VwAE7TWwLU6Cf86krEqiC1tmpoNQ6kgvSKe6mrvYzoRwwyVsjbo541BdKrgBaOB/hgOCfkmgwTVaO+GPUOuJi19miHBBEwFW6FY3RLCj1auSfjjZTNSNfUXL5hvFe0A5oHaHo7wYVHQ1VoxjPghLky++dtTxMMisVpzGGgGwd8aVNk5UgXyYHzBew35N1XXUWHPAYbJwRzhePqjweWp4oB+QwC0rHiPoY8oUVIV/RD+Q4C0o4X4SuC6gM+TKvjfEVVAEj+zthaDMVXRfQrfyMoxBDQHZ+wDMQ+VDI14OAIJ1PMTVb5YBnoHUEFXB0ISDsiE+aNWw64j8krSPN2hDjfGMzB+2WVUGnvxgV5Rr4SFV8vci5PnpSVNBhbR36bRcjaufMgKBof1F5zhIC0h+pOMO+qNszd1h0UqzTnEIWr8qINdhM7dlBvhwEVDjiOSDgcaOkdSQcmz0wOsHLwRF/2IygMaKg6LoAiwhIGlSmERDdw5eidgbGnwwyZaNIM5niqRtGQEpCwZ0MXs98kWu52J96rW/Xdomume/5BiVlfWWL+AGn/eVFY7GMSspmmqkFSjPoB4ySYGQ08mfK0KUKVaYZ3IpGhBqLka92poxFBI6tQJf2kFlQa6EYwSHrAvyetSTDqxc7zYhJkk2aJo2roIcHLNKM7uHTYx3RqYKOQA5oIxSmSdcysaZBJhVUCLhuPcdRRXv4qlRsByBQ2EdAxejNiAPnIwHuSFprTFkj37nH6HpR/AJ/2Oec5HJ7+EySE4UK2vlct1aSpwqJiCBffOEwCXgD8V6tYSfH9eU1RxryZVMlZXts72ut+fvOaDRri99UW8EGocU+H46AMwjenddmY4a9a22f4/Ui503zW464QAGGAQc8FZdk9DcOLUTbblPdgvRlRwWNzc+f6sUWCV/A6rCTjpfRZ6V2zlyazQ3uVQIsAyHoIQgBe3IekbbPTP0ug3x8yx39dSQhpXkgClMGMhHw3BOBfDlqiwAEbEujVF3uJHWm6wX7y1Fb1svnAL+xzIoDshYPZ2FTEiC7xVkIT4lRKO3ly3gDTzgf99rouoDq0IT3szwWeClKQ0Det4yTWBryPdW6mMPgbxH0kyTXvjj5haBHwhPVenhGTnhX5ZePhCesv/MfAUlV3lqwG1vJA13Flq0jJRDwQQX1vif+Y2Plj91YeZd1w3d3pGX5sY1GqvL27cRybGYQEzcQl+QHeY5U5d2le9tZXtlKrcwafnXEBgf00qrywsR+bKddM6Qh32P0vNBPVmVnk0GWPyYf5h1X4pTOEwccJP/pyxKDLE/e0srstqRm2fmRfJR3Vzgk+Z5cM3auA2d+4ueER2w68xybTLK8tDXHSeZRlVMr8/wEj6r872HemNssf7plk+XbuX2YGdC+ZwRwXh/m4eUrPnE5NPnV/wLBHOSjOK9o5gAAAABJRU5ErkJggg=="

